Updates to CMAQv5.3.3 to include WRF-CMAQ changes: 	1.) twoway coupler now in UTILS 	2.) Updates to aqprep and other twoway modules on CMAQ side

diff --git a/UTIL/wrfcmaq_twoway_coupler/assemble b/UTIL/wrfcmaq_twoway_coupler/assemble
--- a/UTIL/wrfcmaq_twoway_coupler/assemble
+++ b/UTIL/wrfcmaq_twoway_coupler/assemble
@@ -1,137 +1,110 @@
 #!/bin/csh
 
-set IOAPI_exist = `env | grep IOAPI | wc -l`
-if (! $IOAPI_exist) then
-   echo ' '
-   echo ' Please setup the path for IOAPI library first and execute this script again'
-   echo ' '
-   echo '    e.g. setenv IOAPI /home/wdx/lib/x86_64/ifc-17.0.3/ioapi_3.1'
-   echo ' '
-   exit
-endif
-
 # type fmm -h for help
 set exist_h = ` echo $argv | grep -e "-h" | wc -w `
-
+ 
 if ($exist_h != 0) then
    goto usage
+endif
+
+if ( !($?wrf_path) ) then
+   echo ' '
+   echo ' Error: Environment variable wrf_path is not set.'
+   echo ' '
+   echo '        Please do this'
+   echo '          setenv wrf_path path_of_wrf_source_code'
+   echo ' '
 else
-   goto checkarg
-endif
+   set wrfpath=$wrf_path
 
-cont:
-
-if (! $create_makefile_only) then
-# modify code in wrf
-  cd wrfcmaq_twoway_coupler
-
-  if (-d misc/orig) then
-     rm -f -r misc/orig
-  endif
-
-  ls -1 */* > __tfile
-
-  set count = `wc -l __tfile`
-
-  @ n = 0
-
-# copy twoway related files to the appropriate directory and keep an old copy
-  while ($n < $count[1])
-    @ n++
-    set temp = `head -n $n __tfile | tail -n 1 | sed 's/\// /' `
-    set directory = $temp[1]
-    set file      = $temp[2]
-    if (($directory != misc) && ($directory != script)) then
-       if ($directory == external) then
-          cp -p $directory/$file ../$directory/io_netcdf
-       else
-          if (-f ../$directory/$file) then
-             if (! -d misc/orig) then
-                mkdir misc/orig
-             endif
-             if (! -d misc/orig/$directory) then
-              mkdir misc/orig/$directory
-             endif
-           mv ../$directory/$file misc/orig/$directory/$file
-          endif
-          cp -p $directory/$file ../$directory
-       endif
-    endif
-  end
-
-  rm -f __tfile
-
-  mv ../clean misc/orig/clean
-  cp -r clean ..
-
-  mv ../Makefile misc/orig/Makefile
-  cp -r Makefile ..
-
-  cd ..
-
-  cp cmaq/complex_number_module.F90 phys/complex_number_module.F
-endif
-
-# create Makefile.twoway
-
-cd cmaq
-
-if (-f mpif.h) then
-   rm -f mpif.h
-endif
-
-cd ..
-
-set found_openmpi = `echo $LD_LIBRARY_PATH | grep openmpi  | wc -l `
-
-set tline = `grep "FORMAT_FIXED    =" configure.wrf`
-if (`echo $tline | grep form | wc -l `) then
-   set compiler = gcc
-else if (`echo $tline | grep Mfixed | wc -l `) then
-   set compiler = pgi
-else if (`echo $tline | grep FI | wc -l `) then
-   set compiler = ifort
-   if ($found_openmpi) then
-      cat configure.wrf | sed 's/=       mpif90 -f90=/=       mpifort -f90=/' > __new
+   if ($#argv == 1) then
+      set reverse = 1
    else
-      cat configure.wrf | sed 's/=       mpif90 -f90=/=       mpiifort -f90=/' > __new
+      set reverse = 0
    endif
-   mv __new configure.wrf
-else
-   echo 'ABORT: Unknow compiler '
-   exit
-endif
 
-if (! $create_makefile_only) then
-# modify configure.wrf
-  wrfcmaq_twoway_coupler/reconfigure
+   set my_list = ( \
+       Makefile \
+       clean \
+       configure \
+       Registry/Registry.EM \
+       Registry/registry.em_shared_collection \
+       arch/Config.pl \
+       dyn_em/module_first_rk_step_part1.F \
+       dyn_em/solve_em.F \
+       dyn_nmm/module_PHYSICS_CALLS.F \
+       main/Makefile \
+       main/depend.common \
+       phys/Makefile \
+       phys/module_ra_rrtmg_sw.F \
+       phys/module_radiation_driver.F \
+       )
+
+   if (! -d $wrfpath) then
+      echo ' '
+      echo " Error: path $wrfpath does not exist. "
+      echo ' '
+   else
+      if ($reverse) then
+         echo ' '
+         echo ' Perform reverse action '
+         echo ' '
+         if (! -d $wrfpath/storage) then
+            echo ' '
+            echo ' Error: directory storage does not exist'
+            echo '        reverse operation cannot be performed'
+            echo ' '
+         else
+            rm -f $wrfpath/Registry/registry.WRF-CMAQ-twoway
+            rm -f $wrfpath/phys/complex_number_module.F
+            rm -f $wrfpath/phys/module_twoway_rrtmg_aero_optical_util.F
+
+            cp -p $wrfpath/storage/external/makefile $wrfpath/external/io_netcdf/makefile 
+
+            foreach item ($my_list)
+              cp -p $wrfpath/storage/$item $wrfpath/$item 
+            end
+         endif
+      else
+         if (! -d $wrfpath/storage) then
+            mkdir $wrfpath/storage
+            mkdir $wrfpath/storage/Registry
+            mkdir $wrfpath/storage/arch
+            mkdir $wrfpath/storage/dyn_em
+            mkdir $wrfpath/storage/dyn_nmm
+            mkdir $wrfpath/storage/external
+            mkdir $wrfpath/storage/main
+            mkdir $wrfpath/storage/phys
+         endif
+
+         # take care all the items in the list
+         foreach item ($my_list)
+           cp -p $wrfpath/$item $wrfpath/storage/$item
+           cp twoway/$item $wrfpath/$item
+         end
+
+         # take care this special file
+         cp -p $wrfpath/external/io_netcdf/makefile $wrfpath/storage/external
+         cp twoway/external/makefile $wrfpath/external/io_netcdf/makefile
+
+         # take care three additional new files
+         cp twoway/Registry/registry.WRF-CMAQ-twoway $wrfpath/Registry
+         cp twoway/phys/complex_number_module.F $wrfpath/phys/complex_number_module.F
+         cp twoway/phys/module_twoway_rrtmg_aero_optical_util.F $wrfpath/phys/module_twoway_rrtmg_aero_optical_util.F
+
+      endif
+   endif
 endif
 
 exit
 
-#---------------------------------------------------------------------
-checkarg:
-
-set count = $#argv
-if ($count == 1) then
-   set create_makefile_only = 1
-else
-   set create_makefile_only = 0
-endif
-
-goto cont
-
-# -------------------------------------------------------------------------
 usage:
+
 echo ' '
-echo ' assemble [ m ] '
+echo ' assemble [ r ] [ -h ]'
 echo ' '
-echo '    where option m to instruct the process to produce Makefile.twoway'
-echo '      in cmaq only'
-echo ' '
-echo ' If you have any comment/question/problem using this script/program, '
-echo ' please contact David Wong at wong.david-c@epa.gov'
+echo '   -h  -- display usage information'
+echo '   with arguement r, it will restore to original files in the WRF directory'
 echo ' '
 
 exit
-
